### ISSUE TITLE
Sheet improvements

### ISSUE THREAD

**Issue by hero101** [alkem-io/github-api#17]
## Description
As a user
I want a few usability improvements
So that I operate easier and efficiently

## Acceptance criteria

- [x] Columns to be ordered
- [ ] Graphs/Visualizations to not be removed from the sheet when exported by the code
- [x] Results available over 100 results
Optional 
- [x] Columns to be auto-fitted based on the content, so the table is readable

**Comment by techsmyth** [comment]
@hero101 this update is working nicely. I have split the last item re keeping spreadsheet structure out into a separate issue, that is of lower priority + that we can pick up later. https://github.com/alkem-io/github-api/issues/19
